module.exports = {
  mySidebar: [
    // ── Overview ──────────────────────────────────────────────────────────────
    {
      type: "category",
      label: "Overview",
      collapsed: false,
      items: [
        "installation/system-requirements",
        "installation/whats-new",
        "release-notes",
      ],
    },

    // ── Accessing the Solution ────────────────────────────────────────────────
    {
      type: "category",
      label: "Accessing the Solution",
      collapsed: true,
      link: {
        type: "doc",
        id: "Files/UI/Solution-Manager/Accessing-the-Solution-Overview",
      },
      items: [
        "Files/UI/Solution-Manager/Logging-In",
        "Files/UI/Solution-Manager/Forgot-Password-Login",
        "Files/UI/Solution-Manager/SM-UI-Layout",
        "Files/UI/Solution-Manager/URL-Shortcuts",
        "Files/UI/Solution-Manager/Keyboard-Shortcuts",
        "Files/UI/Solution-Manager/Responsive-Platform",
      ],
    },

    // ── Concepts ──────────────────────────────────────────────────────────────
    {
      type: "category",
      label: "Concepts",
      collapsed: true,
      link: {
        type: "doc",
        id: "automation-concepts/Concepts-Overview",
      },
      items: [
        "objects/schedules",
        {
          type: "category",
          label: "Jobs",
          collapsed: true,
          link: {
            type: "doc",
            id: "objects/Jobs-Section-Overview",
          },
          items: [
        "objects/jobs",
            {
              type: "category",
              label: "Job Types",
              collapsed: true,
              link: {
                type: "doc",
                id: "job-types/Job-Types-Overview",
              },
              items: [
        "job-types/bis",
                "job-types/container",
                "job-types/file-transfer",
                "job-types/ibm-i",
                "job-types/java",
                "job-types/mcp",
                "job-types/null",
                "job-types/os-2200",
                "job-types/sap-bw",
                "job-types/sap",
                "job-types/sql",
                "job-types/tuxedo-art",
                "job-types/unix",
                "job-types/windows",
                "job-types/zos",
              ],
            },
            "automation-concepts/master-vs-daily",
            "automation-concepts/editing-master-vs-daily",
          ],
        },
        {
          type: "category",
          label: "Schedule Dates",
          collapsed: true,
          link: {
            type: "doc",
            id: "operations/Schedule-Dates-Overview",
          },
          items: [
        "operations/schedule-dates",
            "operations/schedule-names",
            "operations/job-names",
          ],
        },
        {
          type: "category",
          label: "Frequencies",
          collapsed: true,
          link: {
            type: "doc",
            id: "automation-concepts/Frequencies-Section-Overview",
          },
          items: [
        "automation-concepts/frequencies",
            "objects/calendars",
            "operations/building-schedules",
          ],
        },
        {
          type: "category",
          label: "Agents",
          collapsed: true,
          link: {
            type: "doc",
            id: "objects/Agents-Section-Overview",
          },
          items: [
        "objects/machines",
            "objects/machine-groups",
            "automation-concepts/machine-groups",
          ],
        },
        {
          type: "category",
          label: "Properties",
          collapsed: true,
          link: {
            type: "doc",
            id: "objects/Properties-Section-Overview",
          },
          items: [
        "objects/properties",
            "objects/using-properties",
            "objects/defining-properties",
            "automation-concepts/property-expressions",
          ],
        },
        {
          type: "category",
          label: "Instances",
          collapsed: true,
          link: {
            type: "doc",
            id: "automation-concepts/Instances-Section-Overview",
          },
          items: [
        "automation-concepts/named-schedule-instances",
            "objects/remote-instances",
          ],
        },
        {
          type: "category",
          label: "Job and Schedule Statuses",
          collapsed: true,
          link: {
            type: "doc",
            id: "operations/Statuses-Section-Overview",
          },
          items: [
        "operations/status-descriptions",
            "operations/status-change-commands",
          ],
        },
        "objects/thresholds",
        "objects/resources",
        {
          type: "category",
          label: "Job Components",
          collapsed: true,
          items: [
            "job-components/overview",
            "job-components/instances",
            "job-components/frequency",
            "job-components/events",
            "job-components/threshold-resource-updates",
            "job-components/job-dependencies",
            "job-components/threshold-resource-dependencies",
            "job-components/expression-dependencies",
            "job-components/documentation",
            "job-components/tags",
          ],
        },
        "automation-concepts/embedded-scripts",
        "automation-concepts/job-tracking",
        "automation-concepts/file-transfer-jobs",
        "automation-concepts/null-jobs",
        "automation-concepts/time-zones",
      ],
    },

    // ── Administration ────────────────────────────────────────────────────────
    {
      type: "category",
      label: "Administration",
      collapsed: true,
      link: {
        type: "doc",
        id: "administration/Administration-Overview",
      },
      items: [
    {
          type: "category",
          label: "Architecture",
          collapsed: true,
          link: {
            type: "doc",
            id: "server-programs/Architecture-Overview",
          },
          items: [
        "server-programs/introduction",
            "server-programs/licensing",
            "server-programs/service-manager",
            "server-programs/schedule-activity-monitor",
            "server-programs/notify-handler",
            "server-programs/request-router",
            "server-programs/start-time-calculator",
            "server-programs/optional",
            "server-programs/configuration",
            "server-programs/logging",
          ],
        },
        {
          type: "category",
          label: "User Security",
          collapsed: true,
          link: {
            type: "doc",
            id: "administration/User-Security-Overview",
          },
          items: [
    {
              type: "category",
              label: "Authentication",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Authentication-Overview",
              },
              items: [
        "Files/UI/Solution-Manager/Logging-In",
                "Files/UI/Solution-Manager/Forgot-Password-Login",
                "Files/UI/Solution-Manager/Generating-External-Tokens",
              ],
            },
            {
              type: "category",
              label: "RBAC",
              collapsed: true,
              link: {
                type: "doc",
                id: "administration/RBAC-Overview",
              },
              items: [
        "administration/roles",
                "administration/privileges",
                "Files/UI/Solution-Manager/Library/AccessManagement/Access-Management",
                {
                  type: "category",
                  label: "Managing Roles",
                  collapsed: true,
                  link: {
                    type: "doc",
                    id: "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Managing-Roles-Overview",
                  },
                  items: [
        "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Managing-Roles-And-Privileges",
                    "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Adding-Roles",
                    "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Copying-Roles",
                    "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Deleting-Roles",
                    {
                      type: "category",
                      label: "Modifying Roles and Privileges",
                      collapsed: true,
                      link: {
                        type: "doc",
                        id: "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Modifying-Roles-And-Privileges/Modifying-Roles-Overview",
                      },
                      items: [
        "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Modifying-Roles-And-Privileges/Activities",
                        "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Modifying-Roles-And-Privileges/Batch-Users",
                        "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Modifying-Roles-And-Privileges/Department-Activities",
                        "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Modifying-Roles-And-Privileges/General",
                        "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Modifying-Roles-And-Privileges/Resources",
                        "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Modifying-Roles-And-Privileges/Users",
                      ],
                    },
                  ],
                },
                {
                  type: "category",
                  label: "Managing Users",
                  collapsed: true,
                  link: {
                    type: "doc",
                    id: "Files/UI/Solution-Manager/Library/AccessManagement/Users/Managing-Users-Overview",
                  },
                  items: [
        "administration/user-accounts",
                    "Files/UI/Solution-Manager/Library/AccessManagement/Users/Managing-Users",
                    "Files/UI/Solution-Manager/Library/AccessManagement/Users/Adding-Users",
                    "Files/UI/Solution-Manager/Library/AccessManagement/Users/Copying-Users",
                    "Files/UI/Solution-Manager/Library/AccessManagement/Users/Deleting-Users",
                    {
                      type: "category",
                      label: "Modifying Users",
                      collapsed: true,
                      link: {
                        type: "doc",
                        id: "Files/UI/Solution-Manager/Library/AccessManagement/Users/Modifying-Users/Modifying-Users-Overview",
                      },
                      items: [
        "Files/UI/Solution-Manager/Library/AccessManagement/Users/Modifying-Users/General",
                        "Files/UI/Solution-Manager/Library/AccessManagement/Users/Modifying-Users/Roles",
                        "Files/UI/Solution-Manager/Library/AccessManagement/Users/Modifying-Users/Settings",
                      ],
                    },
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Departments",
              collapsed: true,
              items: [
                "objects/departments",
                "Files/UI/Solution-Manager/Library/Departments/Departments",
              ],
            },
            {
              type: "category",
              label: "Access Codes",
              collapsed: true,
              items: [
                "objects/access-codes",
                "Files/UI/Solution-Manager/Library/AccessCodes/AccessCodes",
              ],
            },
            {
              type: "category",
              label: "Auditing",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Library/Logs/Auditing-Overview",
              },
              items: [
        "Files/UI/Solution-Manager/Library/Logs/List-Log-Files",
                "Files/UI/Solution-Manager/Library/Logs/List-Schedule-Builds",
                "Files/UI/Solution-Manager/Library/Logs/List-Archive-Files",
                "Files/UI/Solution-Manager/Library/Logs/Log-File-Details",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Executing Work",
          collapsed: true,
          link: {
            type: "doc",
            id: "administration/Executing-Work-Overview",
          },
          items: [
    {
              type: "category",
              label: "Agents",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Agents-Admin-Overview",
              },
              items: [
        "Files/UI/Solution-Manager/Managing-Agents",
                "Files/UI/Solution-Manager/Performing-Agent-Status-Updates",
              ],
            },
            {
              type: "category",
              label: "Batch Users",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Library/Batch-Users-Overview",
              },
              items: [
        "Files/UI/Solution-Manager/Library/Managing-Batch-Users",
                "Files/UI/Solution-Manager/Library/AccessManagement/Roles/Modifying-Roles-And-Privileges/Batch-Users",
              ],
            },
            {
              type: "category",
              label: "Relay",
              collapsed: true,
              items: [
                "server-programs/network-communications",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "System Configuration",
          collapsed: true,
          link: {
            type: "doc",
            id: "administration/System-Configuration-Overview",
          },
          items: [
        "administration/server-options",
            "Files/UI/Solution-Manager/Library/ServerOptions/View-ServerOptions",
            "Files/UI/Solution-Manager/Library/ServerOptions/Managing-General-Settings",
            "Files/UI/Solution-Manager/Library/ServerOptions/Managing-Logging-Settings",
            "Files/UI/Solution-Manager/Library/ServerOptions/Managing-Security-Settings",
            "Files/UI/Solution-Manager/Library/ServerOptions/Managing-Notification-Settings",
            "Files/UI/Solution-Manager/Library/ServerOptions/Managing-SMTP-Settings",
            "Files/UI/Solution-Manager/Library/ServerOptions/Managing-Vision-Settings",
            "Files/UI/Solution-Manager/Library/ServerOptions/Managing-Time-Settings",
            "Files/UI/Solution-Manager/Library/ServerOptions/Managing-SSO-Configurations",
            "Files/UI/Solution-Manager/Library/ServerOptions/Reset-Settings",
            "installation/configuration",
            "installation/install",
            "installation/upgrade",
            "installation/breaking-changes",
            "installation/components",
            "installation/docker",
            "installation/database-scripts",
            {
              type: "category",
              label: "Database",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/Database-Information/Database-Overview",
              },
              items: [
        "Files/Database-Information/Failover-Scenarios",
                "Files/Database-Information/Manual-Setup-for-Microsoft-SQL-Replication",
                "Files/Database-Information/Setup-for-Automatic-Microsoft-SQL-Replication",
                "Files/Database-Information/Failover-and-Recovery-with-Replication",
                "Files/Database-Information/Setup-for-Automatic-Microsoft-SQL-Mirroring",
                "Files/Database-Information/Manual-Database-Backups-and-Restoration",
                "Files/Database-Information/OpCon-Data-Maintenance",
                "Files/Database-Information/Database-Mirroring-Checklist",
                "Files/Database-Information/Database-Replication-Checklist",
              ],
            },
          ],
        },
      ],
    },

    // ── Development ───────────────────────────────────────────────────────────
    {
      type: "category",
      label: "Development",
      collapsed: true,
      link: {
        type: "doc",
        id: "Files/UI/Solution-Manager/Library/Development-Overview",
      },
      items: [
    {
          type: "category",
          label: "Creating a Workflow",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/Studio/Workflow-Overview",
          },
          items: [
    {
              type: "category",
              label: "Define Schedule",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Studio/Define-Schedule-Overview",
              },
              items: [
        "objects/schedules",
                "Files/UI/Solution-Manager/Studio/Managing-Studio",
                {
                  type: "category",
                  label: "Canvas",
                  collapsed: true,
                  link: {
                    type: "doc",
                    id: "Files/UI/Solution-Manager/Studio/Canvas/Canvas-Overview",
                  },
                  items: [
        "Files/UI/Solution-Manager/Studio/Canvas/Adding-Master-Schedules",
                    "Files/UI/Solution-Manager/Studio/Canvas/Copying-Master-Schedules",
                    "Files/UI/Solution-Manager/Studio/Canvas/Deleting-Master-Schedules",
                    "Files/UI/Solution-Manager/Studio/Canvas/Editing-Master-Schedules",
                    "Files/UI/Solution-Manager/Studio/Canvas/Viewing-Master-Schedules/Viewing-Master-Schedules",
                    "Files/UI/Solution-Manager/Studio/Canvas/Isolate-Dependency-Chain",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Add Jobs",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Library/MasterJobs/Add-Jobs-Overview",
              },
              items: [
        "objects/jobs",
                "Files/UI/Solution-Manager/Library/MasterJobs/Adding-Master-Jobs",
                "Files/UI/Solution-Manager/Library/MasterJobs/Copying-Master-Jobs",
                "Files/UI/Solution-Manager/Library/MasterJobs/Moving-Master-Jobs",
                "Files/UI/Solution-Manager/Library/MasterJobs/Deleting-Master-Jobs",
                "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-Master-Jobs-Cross-References",
                {
                  type: "category",
                  label: "Viewing and Updating Master Jobs",
                  collapsed: true,
                  link: {
                    type: "doc",
                    id: "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-Updating-Overview",
                  },
                  items: [
        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Accessing-Master-Jobs",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-General-Info",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Documentation",
                    {
                      type: "category",
                      label: "Job Task Details",
                      collapsed: true,
                      link: {
                        type: "doc",
                        id: "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/Job-Task-Details-Overview",
                      },
                      items: [
        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/Container-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/File-Transfer-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/IBMi-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/Null-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/SAP-BW-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/Os2200-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/SAP-R3-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/SQL-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/Unix-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/Windows-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/MCP-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/ZOS-Job-Details",
                        "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/JobTaskDetails/BIS-Job-Details",
                      ],
                    },
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Tags",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Frequencies",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Events",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Instance-Properties",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Job-Dependencies",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Expression-Dependencies",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Resource-Dependencies",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Threshold-Dependencies",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Resource-Updates",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Threshold-Updates",
                    "Files/UI/Solution-Manager/Library/MasterJobs/Viewing-And-Updating-Master-Jobs/Viewing-And-Updating-Notification-Triggers",
                  ],
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Scripts",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/Library/Scripts/Scripts-Overview",
          },
          items: [
        "Files/UI/Solution-Manager/Library/Scripts/Managing-Scripts",
            "Files/UI/Solution-Manager/Library/Scripts/Managing-Script-Versions",
            "Files/UI/Solution-Manager/Library/Scripts/Managing-Script-Types",
            "Files/UI/Solution-Manager/Library/Scripts/Managing-Script-Runners",
          ],
        },
        {
          type: "category",
          label: "Frequencies",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/Library/Frequencies/Frequencies-Dev-Overview",
          },
          items: [
        "Files/UI/Solution-Manager/Library/Frequencies/Managing-Frequencies",
            "Files/UI/Solution-Manager/Library/Frequencies/Editing-Frequencies",
            "Files/UI/Solution-Manager/Library/Frequencies/Forecasting-Frequencies",
          ],
        },
        "Files/UI/Solution-Manager/Library/Global-Properties",
        "Files/UI/Solution-Manager/Library/MachineGroups/MachineGroups",
        "Files/UI/Solution-Manager/Library/Managing-Tags",
      ],
    },

    // ── Operations ────────────────────────────────────────────────────────────
    {
      type: "category",
      label: "Operations",
      collapsed: true,
      link: {
        type: "doc",
        id: "Files/UI/Solution-Manager/Operations-Overview",
      },
      items: [
        "Files/UI/Solution-Manager/Viewing-Notification-Acknowledgement",
        {
          type: "category",
          label: "Navigating Operations",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/Navigating-Operations-Overview",
          },
          items: [
        "Files/UI/Solution-Manager/Managing-Operations",
            "Files/UI/Solution-Manager/Managing-Daily-Processes",
            "Files/UI/Solution-Manager/Managing-Schedules",
            "Files/UI/Solution-Manager/Configuring-Settings",
            "Files/UI/Solution-Manager/Configuring-Application-Settings",
            "Files/UI/Solution-Manager/Accessing-and-Updating-Profile-Settings",
            "Files/UI/Solution-Manager/Configuring-Account-Settings",
          ],
        },
        "operations/schedule-dates",
        {
          type: "category",
          label: "Schedule Actions",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/Schedule-Actions-Overview",
          },
          items: [
        "Files/UI/Solution-Manager/Performing-Schedule-Status-Changes",
            "Files/UI/Solution-Manager/Performing-Bulk-Job-Status-Updates-Schedule-Level",
            "Files/UI/Solution-Manager/Performing-Bulk-Job-Status-Updates-Date-Level",
            "operations/editing-schedules",
            "operations/deleting-schedules",
            "Files/UI/Solution-Manager/Using-Schedule-Build-Queue",
            "Files/UI/Solution-Manager/Performing-Schedule-Checks",
          ],
        },
        {
          type: "category",
          label: "Job Actions",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/Job-Actions-Overview",
          },
          items: [
        "Files/UI/Solution-Manager/Viewing-Job-Configuration",
            "Files/UI/Solution-Manager/Accessing-Job-Summary",
            "Files/UI/Solution-Manager/Using-PERT-View",
            "Files/UI/Solution-Manager/Viewing-Job-Output",
            "operations/job-output",
            "Files/UI/Solution-Manager/Accessing-Job-Executions-History",
            "Files/UI/Solution-Manager/Performing-Job-Status-Changes",
            {
              type: "category",
              label: "Daily Job Definition",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Daily-Job-Definition-Overview",
              },
              items: [
        "Files/UI/Solution-Manager/Accessing-Daily-Job-Definition",
                "Files/UI/Solution-Manager/Copying-Daily-Job-to-Master",
                "Files/UI/Solution-Manager/Viewing-and-Updating-General-Info",
                "Files/UI/Solution-Manager/Viewing-and-Updating-Documentation",
                {
                  type: "category",
                  label: "Job Task Details",
                  collapsed: true,
                  link: {
                    type: "doc",
                    id: "Files/UI/Solution-Manager/Daily-Job-Task-Details-Overview",
                  },
                  items: [
        "Files/UI/Solution-Manager/Viewing-and-Updating-Job-Task-Details",
                    "Files/UI/Solution-Manager/Viewing-Null-Job-Details",
                    "Files/UI/Solution-Manager/Updating-IBMi-Job-Details",
                    "Files/UI/Solution-Manager/Updating-SAP-BW-Job-Details",
                    "Files/UI/Solution-Manager/Updating-SAP-R3-Job-Details",
                    "Files/UI/Solution-Manager/Viewing-Container-Job-Details",
                    "Files/UI/Solution-Manager/Updating-Windows-Job-Details",
                    "Files/UI/Solution-Manager/Updating-UNIX-Job-Details",
                    "Files/UI/Solution-Manager/Updating-File-Transfer-Job-Details",
                    "Files/UI/Solution-Manager/Updating-mcp-Job-Details",
                  ],
                },
                "Files/UI/Solution-Manager/Viewing-and-Updating-Job-Frequencies",
                "Files/UI/Solution-Manager/Viewing-and-Updating-Instance-Properties",
                "Files/UI/Solution-Manager/Viewing-and-Updating-Expression-Dependencies",
                "Files/UI/Solution-Manager/Viewing-and-Updating-Resource-Dependencies",
                "Files/UI/Solution-Manager/Viewing-and-Updating-Threshold-Dependencies",
                "Files/UI/Solution-Manager/Viewing-and-Updating-Resource-Updates",
                "Files/UI/Solution-Manager/Viewing-and-Updating-Threshold-Updates",
              ],
            },
            "Files/UI/Solution-Manager/Adding-Jobs-to-Daily-Schedules",
            "operations/adding-jobs",
            "Files/UI/Solution-Manager/Deleting-Schedules-and-Jobs",
          ],
        },
        {
          type: "category",
          label: "Containers",
          collapsed: true,
          link: {
            type: "doc",
            id: "operations/Containers-Overview",
          },
          items: [
        "operations/containers",
            "operations/window-to-host",
            "operations/SAP-Job-Menu-Options",
          ],
        },
        {
          type: "category",
          label: "Otto AI Assistant",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/Otto/Otto-Overview",
          },
          items: [
        "Files/UI/Solution-Manager/Otto/Otto-Chatbot",
            {
              type: "category",
              label: "Skills",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Otto/Skills/Otto-Skills-Section-Overview",
              },
              items: [
        "Files/UI/Solution-Manager/Otto/Skills/Skills-Overview",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Add-Daily-Job",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Build-Schedule",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Delete-Daily-Job",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Get-Failed-Jobs",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Get-Failed-Schedules",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Perform-A-Fast-Schedule-Check",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Retrieve-Application-Log",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Restart-Failed-Jobs",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Summarize-Schedule-Build",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Update-Job-Status",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Update-Machine-Status",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Update-Schedule-Status",
                "Files/UI/Solution-Manager/Otto/Skills/Skill-Retrieve-Job-Output",
              ],
            },
          ],
        },
      ],
    },

    // ── Self Service ──────────────────────────────────────────────────────────
    {
      type: "category",
      label: "Self Service",
      collapsed: true,
      link: {
        type: "doc",
        id: "Files/UI/Solution-Manager/Self-Service-Section-Overview",
      },
      items: [
        "Files/UI/Solution-Manager/Managing-Self-Service",
        "Files/UI/Solution-Manager/Creating-Service-Requests",
        "Files/UI/Solution-Manager/Editing-Service-Requests",
        "Files/UI/Solution-Manager/Copying-Service-Requests",
        "Files/UI/Solution-Manager/Deleting-Service-Requests",
        "Files/UI/Solution-Manager/Disabling_Hiding-Service-Requests",
        "Files/UI/Solution-Manager/Stylizing-Service-Requests",
        "Files/UI/Solution-Manager/Running-Service-Requests",
        "Files/UI/Solution-Manager/Filtering-Service-Requests",
        "Files/UI/Solution-Manager/Viewing-Service-Request-Process-Indicators",
        "Files/UI/Solution-Manager/Working-in-Admin-Mode",
        "Files/UI/Solution-Manager/Working-in-User-Mode",
        {
          type: "category",
          label: "User Inputs",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/User-Inputs-Overview",
          },
          items: [
        "Files/UI/Solution-Manager/Setting-up-User-Inputs",
            "Files/UI/Solution-Manager/Configuring-Master-Job-User-Inputs",
            "Files/UI/Solution-Manager/Configuring-Master-Schedule-User-Inputs",
            "Files/UI/Solution-Manager/Configuring-Text-User-Inputs",
            "Files/UI/Solution-Manager/Configuring-Number-User-Inputs",
            "Files/UI/Solution-Manager/Configuring-Choice-User-Inputs",
            "Files/UI/Solution-Manager/Configuring-Date-User-Inputs",
            "Files/UI/Solution-Manager/Configuring-Text-Collection-User-Inputs",
          ],
        },
      ],
    },

    // ── Vision ────────────────────────────────────────────────────────────────
    {
      type: "category",
      label: "Vision",
      collapsed: true,
      link: {
        type: "doc",
        id: "Files/UI/Solution-Manager/Vision-Section-Overview",
      },
      items: [
        "Files/UI/Solution-Manager/Working-with-Vision",
        {
          type: "category",
          label: "Live",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/Vision-Live-Overview",
          },
          items: [
        "Files/UI/Solution-Manager/Viewing-Cards-in-Vision-Live",
            {
              type: "category",
              label: "Admin Mode",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Vision-Admin-Mode-Overview",
              },
              items: [
        "Files/UI/Solution-Manager/Working-in-Admin-Mode_Vision",
                "Files/UI/Solution-Manager/Enabling-Admin-Mode-Editing_Vision",
                "Files/UI/Solution-Manager/Managing-Vision-Settings",
                "Files/UI/Solution-Manager/Managing-Vision-Frequencies",
                "Files/UI/Solution-Manager/Managing-Vision-Actions",
                "Files/UI/Solution-Manager/Managing-Vision-Remote-Instances",
              ],
            },
            {
              type: "category",
              label: "User Mode",
              collapsed: true,
              items: [
                "Files/UI/Solution-Manager/Working-in-User-Mode_Vision",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Health",
          collapsed: true,
          items: [
            "Files/UI/Solution-Manager/Viewing-Vision-Health",
          ],
        },
        {
          type: "category",
          label: "Cards",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Solution-Manager/Vision-Cards-Overview",
          },
          items: [
        "Files/UI/Solution-Manager/Creating-Cards",
            "Files/UI/Solution-Manager/Editing-Cards",
            "Files/UI/Solution-Manager/Deleting-Cards",
            "Files/UI/Solution-Manager/Creating-Categories",
          ],
        },
      ],
    },

    // ── Reference ─────────────────────────────────────────────────────────────
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      link: {
        type: "doc",
        id: "reference/Reference-Section-Overview",
      },
      items: [
    {
          type: "category",
          label: "Events",
          collapsed: true,
          link: {
            type: "doc",
            id: "events/Events-Section-Overview",
          },
          items: [
        "events/introduction",
            "events/defining",
            "events/types",
          ],
        },
        {
          type: "category",
          label: "Notifications",
          collapsed: true,
          link: {
            type: "doc",
            id: "notifications/Notifications-Section-Overview",
          },
          items: [
        "notifications/Notification-Triggers",
            "notifications/Notification-Configuration",
            "notifications/Components",
            "notifications/Escalation",
            "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTriggers",
            "Files/UI/Solution-Manager/Library/NotificationCategories/NotificationCategories",
            "Files/UI/Solution-Manager/Library/NotificationGroups/NotificationGroups",
            {
              type: "category",
              label: "Notification Types",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/Notification-Types-Overview",
              },
              items: [
        "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/Copy-Notification-Trigger",
                "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/Look-up-Notification-Sources",
                "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/Email",
                "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/Text-Message",
                "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/OpCon-Events",
                "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/Windows-Event-Log",
                "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/Network-Message",
                "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/SNMP-Trap",
                "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/Run-Command",
                "Files/UI/Solution-Manager/Library/NotificationTriggers/NotificationTypes/SPO-Event-Report",
              ],
            },
            {
              type: "category",
              label: "Escalation Manager",
              collapsed: true,
              link: {
                type: "doc",
                id: "Files/UI/Solution-Manager/Library/EscalationManager/Escalation-Manager-Overview",
              },
              items: [
        "Files/UI/Solution-Manager/Library/EscalationManager/Escalation-Manager",
                "Files/UI/Solution-Manager/Library/EscalationManager/Managing-Escalation-Rules",
                "Files/UI/Solution-Manager/Library/EscalationManager/Managing-Escalation-Groups",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Reports",
          collapsed: true,
          items: [
            "reports/overview",
            "reports/predefined",
            "reports/custom",
            "reports/reporting-service",
            "Files/UI/Solution-Manager/Library/Reporting/List-Reports",
            "Files/UI/Solution-Manager/Library/Reporting/Annual-Plan-By-Calendar-Dates-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Audit-History-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Comparative-Job-Execution-Statistics-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Cross-Reference-Schedules-And-Jobs-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Current-Global-Properties-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Current-Resource-Values-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Current-Threshold-Values-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Daily-Job-Information-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Event-Details-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Frequencies-And-Associated-Jobs-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Job-Dependencies-And-Documentation-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Master-Job-Information-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Roles-And-Privileges-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Schedule-Job-History-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Unique-Task-Count-Report",
            "Files/UI/Solution-Manager/Library/Reporting/Users-And-Privileges-Report",
          ],
        },
        {
          type: "category",
          label: "Utilities",
          collapsed: true,
          items: [
            "utilities/overview",
            {
              type: "category",
              label: "Command-line Utilities",
              collapsed: true,
              items: [
                "utilities/Command-line-Utilities/Introduction",
                "utilities/Command-line-Utilities/Adminstrative-Stored-Procedures",
                "utilities/Command-line-Utilities/Audit-History-Cleanup",
                "utilities/Command-line-Utilities/BIRT-Report-Generator",
                "utilities/Command-line-Utilities/Check-Job-Termination",
                "utilities/Command-line-Utilities/Check-Schedule-and-Job-Status",
                "utilities/Command-line-Utilities/Chronoman",
                "utilities/Command-line-Utilities/DoBatch",
                "utilities/Command-line-Utilities/Job-History-Cleanup",
                "utilities/Command-line-Utilities/Pingman",
                "utilities/Command-line-Utilities/Schedule-Extract-Command-line-Interface",
                "utilities/Command-line-Utilities/SMA-Evaluate-Expression",
                "utilities/Command-line-Utilities/SMADirectory",
                "utilities/Command-line-Utilities/SMAGetServiceStatus",
                "utilities/Command-line-Utilities/SMAHoliday",
                "utilities/Command-line-Utilities/SMALogEvent",
                "utilities/Command-line-Utilities/SMASetRMFileName",
                "utilities/Command-line-Utilities/Synch-SAP",
              ],
            },
            {
              type: "category",
              label: "Graphical Utilities",
              collapsed: true,
              items: [
                "utilities/Graphical-Utilities/Introduction",
                "utilities/Graphical-Utilities/Legacy-Audit-Management",
                "utilities/Graphical-Utilities/Schedule-Import_Export",
                "utilities/Graphical-Utilities/SMA-OpCon-Configuration-Utility",
              ],
            },
            {
              type: "category",
              label: "SMA Dynamic Data Input",
              collapsed: true,
              items: [
                "utilities/SMA-Dynamic-Data-Input/Introduction",
                "utilities/SMA-Dynamic-Data-Input/Configuration",
                "utilities/SMA-Dynamic-Data-Input/Creating-Data-Input-Files",
                "utilities/SMA-Dynamic-Data-Input/SMADDI-Message-Types",
                "utilities/SMA-Dynamic-Data-Input/Data-Input-Message-Elements",
                "utilities/SMA-Dynamic-Data-Input/jobdata-Platform-specific-Elements",
              ],
            },
            {
              type: "category",
              label: "SMA Resource Monitor",
              collapsed: true,
              items: [
                "utilities/SMA-Resource-Monitor/Introduction",
                "utilities/SMA-Resource-Monitor/Summary-Information",
                "utilities/SMA-Resource-Monitor/Wizards",
                "utilities/SMA-Resource-Monitor/Tools",
                "utilities/SMA-Resource-Monitor/Service",
              ],
            },
          ],
        },
        "reference/best-practices",
        "reference/property-expressions-syntax",
        "reference/Operations-Machine-Messages",
        "reference/Operations-File-Transfer-Messages",
        "reference/Windows-System-Errors",
        "Files/UI/Solution-Manager/Library/LicenseSupport/License-Support",
        "Files/UI/Solution-Manager/Library/CloudEventsTriggers/CloudEventsTriggers",
        "file-locations",
        "components",
      ],
    },

    // ── Enterprise Manager (legacy) ───────────────────────────────────────────
    {
      type: "category",
      label: "Enterprise Manager",
      collapsed: true,
      link: {
        type: "doc",
        id: "Files/UI/Enterprise-Manager/Enterprise-Manager-Overview",
      },
      items: [
        "Files/UI/Enterprise-Manager/Logging-In",
        {
          type: "category",
          label: "Understanding the Layout",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Enterprise-Manager/Layout-Overview",
          },
          items: [
        "Files/UI/Enterprise-Manager/EM-UI-Layout",
            "Files/UI/Enterprise-Manager/Menus",
            "Files/UI/Enterprise-Manager/Navigation-Panel",
            "Files/UI/Enterprise-Manager/Information-Bar",
            "Files/UI/Enterprise-Manager/Keyboard-Shortcuts",
          ],
        },
        {
          type: "category",
          label: "Getting Started",
          collapsed: true,
          link: {
            type: "doc",
            id: "Files/UI/Enterprise-Manager/Getting-Started-Overview",
          },
          items: [
        "Files/UI/Enterprise-Manager/Managing-Connection-Profiles",
            "Files/UI/Enterprise-Manager/Setting-Preferences",
            "Files/UI/Enterprise-Manager/Setting-Language",
            "Files/UI/Enterprise-Manager/Receiving-Installation-Details",
          ],
        },
        {
          type: "category",
          label: "Solution Manager",
          collapsed: true,
          items: [
            "Files/UI/Enterprise-Manager/Working-with-Solution-Manager",
            "Files/UI/Enterprise-Manager/Using-Home",
            "Files/UI/Enterprise-Manager/Using-Operations",
            "Files/UI/Enterprise-Manager/Using-Vision",
            "Files/UI/Enterprise-Manager/Using-Self-Service",
            "Files/UI/Enterprise-Manager/Using-Profile",
          ],
        },
        {
          type: "category",
          label: "Administration",
          collapsed: true,
          items: [
            "Files/UI/Enterprise-Manager/Working-with-Administration",
            "Files/UI/Enterprise-Manager/Using-Quick-Search",
            "Files/UI/Enterprise-Manager/Using-Schedule-Master",
            "Files/UI/Enterprise-Manager/Using-Job-Master",
            "Files/UI/Enterprise-Manager/Using-Workflow-Designer",
            "Files/UI/Enterprise-Manager/Managing-Calendars",
            "Files/UI/Enterprise-Manager/Managing-Global-Properties",
            "Files/UI/Enterprise-Manager/Managing-Thresholds",
            "Files/UI/Enterprise-Manager/Managing-Resources",
            "Files/UI/Enterprise-Manager/Managing-Machines",
            "Files/UI/Enterprise-Manager/Managing-Machine-Groups",
            "Files/UI/Enterprise-Manager/Managing-Remote-Instances",
            "Files/UI/Enterprise-Manager/Managing-Server-Options",
            "Files/UI/Enterprise-Manager/Using-Administration-Tools",
          ],
        },
        {
          type: "category",
          label: "Operation",
          collapsed: true,
          items: [
            "Files/UI/Enterprise-Manager/Working-with-Operation",
            "Files/UI/Enterprise-Manager/Using-List-View",
            "Files/UI/Enterprise-Manager/Using-Matrix-View",
            "Files/UI/Enterprise-Manager/Using-Gantt-View",
            "Files/UI/Enterprise-Manager/Using-PERT-View",
            "Files/UI/Enterprise-Manager/Using-Bar-Chart-View",
            "Files/UI/Enterprise-Manager/Using-Pie-Chart-View",
            "Files/UI/Enterprise-Manager/Using-Workload-Chart-View",
            "Files/UI/Enterprise-Manager/Using-Machines-Status-View",
            "Files/UI/Enterprise-Manager/Using-Daily-Maintenance-View",
            "Files/UI/Enterprise-Manager/Managing-Schedules",
            "Files/UI/Enterprise-Manager/Using-Escalation-Acknowlegement",
            "Files/UI/Enterprise-Manager/Using-Secondary-Windows",
            "Files/UI/Enterprise-Manager/Using-Operation-Tools",
          ],
        },
        {
          type: "category",
          label: "Security",
          collapsed: true,
          items: [
            "Files/UI/Enterprise-Manager/Working-with-Security",
            "Files/UI/Enterprise-Manager/Managing-Roles",
            "Files/UI/Enterprise-Manager/Managing-User-Accounts",
            "Files/UI/Enterprise-Manager/Managing-Batch-Users",
            "Files/UI/Enterprise-Manager/Managing-Departments",
            "Files/UI/Enterprise-Manager/Managing-Access-Codes",
            "Files/UI/Enterprise-Manager/Managing-Privileges",
            "Files/UI/Enterprise-Manager/Using-Security-Tools",
          ],
        },
        {
          type: "category",
          label: "Management",
          collapsed: true,
          items: [
            "Files/UI/Enterprise-Manager/Working-with-Management",
            "Files/UI/Enterprise-Manager/Using-Audit-Management",
            "Files/UI/Enterprise-Manager/Using-History-Management",
            "Files/UI/Enterprise-Manager/Using-Notification-Manager",
            "Files/UI/Enterprise-Manager/Using-Escalation-Manager",
            "Files/UI/Enterprise-Manager/Using-Schedule-Extract",
            "Files/UI/Enterprise-Manager/Using-Tag-Manager",
            "Files/UI/Enterprise-Manager/Using-Frequency-Manager",
            "Files/UI/Enterprise-Manager/Using-Management-Tools",
          ],
        },
        {
          type: "category",
          label: "External Tools",
          collapsed: true,
          items: [
            "Files/UI/Enterprise-Manager/Working-with-External-Tools",
            "Files/UI/Enterprise-Manager/Configuring-the-Installation-Directory",
            "Files/UI/Enterprise-Manager/Opening-Import-Export",
            "Files/UI/Enterprise-Manager/Opening-Windows-Tools",
            "Files/UI/Enterprise-Manager/Adding-External-Tools",
          ],
        },
        {
          type: "category",
          label: "Enterprise Information",
          collapsed: true,
          items: [
            "Files/UI/Enterprise-Manager/Working-with-Enterprise-Information",
            "Files/UI/Enterprise-Manager/Using-Reports",
            "Files/UI/Enterprise-Manager/Using-Logs",
            "Files/UI/Enterprise-Manager/Using-Information-Tools",
          ],
        },
        {
          type: "category",
          label: "Scripts",
          collapsed: true,
          items: [
            "Files/UI/Enterprise-Manager/Working-with-Scripts",
            "Files/UI/Enterprise-Manager/Using-Script-Repository",
            "Files/UI/Enterprise-Manager/Managing-Script-Runners",
            "Files/UI/Enterprise-Manager/Managing-Script-Types",
            "Files/UI/Enterprise-Manager/Using-Scripts-Tools",
          ],
        },
        {
          type: "category",
          label: "Enterprise Support",
          collapsed: true,
          items: [
            "Files/UI/Enterprise-Manager/Working-with-Enterprise-Support",
            "Files/UI/Enterprise-Manager/Getting-Support-Information",
            "Files/UI/Enterprise-Manager/Reporting-Problems",
            "Files/UI/Enterprise-Manager/Accessing-Application-Logs",
          ],
        },
      ],
    },

    // ── REST API ──────────────────────────────────────────────────────────────
    {
      type: "link",
      label: "REST API Docs",
      href: "https://help.smatechnologies.com/opcon/core/api/26-0.html",
    },
  ],
};
