name: deploy-main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
      # copy content to new app
      - run: azcopy_v10 copy './docs' '${{ secrets.HELP_CONTENT_URL }}/content/${{ github.repository }}?${{ secrets.HELP_CONTENT_TOKEN }}' --recursive
      - run: azcopy_v10 copy './static' '${{ secrets.HELP_CONTENT_URL }}/content/${{ github.repository }}?${{ secrets.HELP_CONTENT_TOKEN }}' --recursive
      - run: azcopy_v10 copy './sidebars.js' '${{ secrets.HELP_CONTENT_URL }}/content/${{ github.repository }}?${{ secrets.HELP_CONTENT_TOKEN }}'
      - run: azcopy_v10 copy './versioned_docs/*' '${{ secrets.HELP_CONTENT_URL }}/versioned-content/opcon-docs_versioned_docs/?${{ secrets.HELP_CONTENT_TOKEN }}' --recursive
      - run: azcopy_v10 copy './versioned_sidebars/*' '${{ secrets.HELP_CONTENT_URL }}/versioned-content/opcon-docs_versioned_sidebars/?${{ secrets.HELP_CONTENT_TOKEN }}' --recursive
      - run: azcopy_v10 copy './versions.json' '${{ secrets.HELP_CONTENT_URL }}/versioned-content/opcon-docs_versions.json?${{ secrets.HELP_CONTENT_TOKEN }}'
      # publish compiled output to existing app
      - run: yarn install
      - run: yarn build
      - run: azcopy_v10 copy 'build/*' '${{ secrets.DOCS_STORAGE_URL }}/${{ secrets.DOCS_STORAGE_PATH }}?${{ secrets.DOCS_STORAGE_KEY }}' --recursive
