name: deploy-22.8

on:
  push:
    branches: [ release/22.8 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
      - run: azcopy_v10 copy 'build/*' '${{ secrets.DOCS_STORAGE_URL }}/${{ secrets.DOCS_STORAGE_PATH_22_8 }}?${{ secrets.DOCS_STORAGE_KEY }}' --recursive
